name: Python Hello World

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create Python Hello World
        run: echo "print('Hello, World!')" > hello.py

      - name: Archive Hello World
        uses: actions/upload-artifact@v2
        with:
          name: python-hello-world
          path: hello.py
